version: '3.8'

services:
  allora-mcp:
    build: .
    environment:
      - MCP_TRANSPORT=stdio
      - ALLORA_API_KEY=${ALLORA_API_KEY}
      - ALLORA_CHAIN_SLUG=${ALLORA_CHAIN_SLUG:-TESTNET}
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check'); process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - allora-network

networks:
  allora-network:
    driver: bridge
